sudo: false
language: python
cache: pip
python:
    - "2.7"
addons:
    postgresql: "9.4"
services:
    - postgresql
env:
    global:
        - SECRET_KEY=SecretKeyForTravis
        - DATABASE_URL="postgres://postgres@localhost:5432/travis_ci_test"
install:
    - psql -U postgres -c "create extension postgis"
    - pip install -r requirements.txt
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    - python manage.py migrate --noinput
script:
    - python manage.py test -v 0 prs2.referral.test_models
