language: python
cache: pip
dist: trusty
sudo: required
python:
    - 2.7
    - 3.5
addons:
    postgresql: 9.5
    apt:
        packages:
            - postgresql-9.5-postgis-2.3
services:
    - postgresql
branches:
    only:
        - master
env:
    global:
        - SECRET_KEY=SecretKeyForTravis
        - DATABASE_URL="postgis://postgres@localhost:5432/travis_ci_test"
before_install:
    - sudo apt install -y libgdal-dev
install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install -r requirements.txt
    - pip install coveralls
before_script:
    - psql -U postgres -c "create database travis_ci_test;"
    - psql -U postgres -d travis_ci_test -c "create extension postgis;"
    - python manage.py migrate --noinput
script:
    - coverage run --source="." manage.py test
after_success:
    - coveralls
