language: python
python:
    - "2.7"
services:
    - postgresql
env:
    - SECRET_KEY=SecretKeyForTravis
    - DATABASE_URL="postgres://postgres@localhost:5432/py27-django-19-postgres"
install:
    - pip install -r requirements.txt
before_script:
    - python manage.py migrate --noinput
script:
    - python manage.py test -v 0 prs2.referral.test_models
